package rests
@bashUrl=http://localhost:8002/v1/2024


### User Registration
POST {{bashUrl}}/user/register
Content-type: application/json

{
"email" : "nguyenhoanghai0507@gmail.com",
"purpose" : "test"
}