package rests
@bashUrl=http://localhost:8002/v1/2024


### User Registration
POST {{bashUrl}}/user/register
Content-type: application/json

{
  "verify_key": "nguyenhoanghai0507@gmail.com",
  "verify_purpose": "TEST_USER",
  "verify_type": 1
}


### JAVA User Registration
POST http://10.56.66.54:8082/email/send_text
Content-type: application/json

{
  "toEmail": "nguyenhoanghai0507@gmail.com",
  "subject": "Long btc nhé",
  "messageBody": "8030104659999",
  "attachment": "MB-HCM"
}