// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package wire

import (
	"github.com/nhh57/go-ecommerce-backend-api/internal/controller"
	"github.com/nhh57/go-ecommerce-backend-api/internal/repo"
	"github.com/nhh57/go-ecommerce-backend-api/internal/service"
)

// Injectors from user.wire.go:

func InitUserRouterHanlder() (*controller.UserController, error) {
	iUserRepository := repo.NewUserRepository()
	iUserAuthenRepository := repo.NewUserAuthenRepository()
	iUserService := service.NewUserService(iUserRepository, iUserAuthenRepository)
	userController := controller.NewUserController(iUserService)
	return userController, nil
}
