server:
  port: 8082
  model: "dev"
mysql:
  host: localhost
  port: 3316
  username: root
  password: root1234
  dbName: shopDev
  maxIdleConns: 10
  maxOpenConns: 100
  conMaxLifetime: 3600
logger:
  log_level: debug
  file_log_name: "../storages/logs/dev.xxx.logs"
  max_size: 1024
  max_backups: 30
  max_age: 7
  compress: true
redis:
  host: localhost
  port: 6319
  password:
  database: 0
jwt:
  TOKEN_HOUR_LIFESPAN: 1
  JWT_EXPIRATION: 1h
  API_SECRET_KEY: "xxx.yyy.zzz"