server:
  port: 8082
databases:
- user: admin
  password: admin
  host: localhost
  dbName: shopDEV
  databases:
- user: order
  password: admin
  host: localhost
  dbName: shopDEV
security:
  jwt:
    key: abc123
